/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-01 03:43:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dto.ReviewDto;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import data.dto.ProductDto;
import data.dao.mainDao;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("data.dto.ReviewDto");
    _jspx_imports_classes.add("data.dao.mainDao");
    _jspx_imports_classes.add("data.dto.ProductDto");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://unpkg.com/swiper/swiper-bundle.min.css\" />\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("<title>메인페이지</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* md pick 디자인 */\r\n");
      out.write(".summary_desc {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	letter-spacing: 0;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".md_pick .listmain_cont .list .infomation .info {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	height: 230px; /*mdpick 길이 조절*/\r\n");
      out.write("	flex-flow: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".md_pick .listmain_cont .list .infomation .info .title {\r\n");
      out.write("	font-family: Montserrat;\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	color: #141414;\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".md_pick .listmain_cont .list .infomation {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".md_pick .listmain_cont .list .infomation .info a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".md_pick .listmain_cont .list .infomation .info .summary_desc {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	line-height: 28px;\r\n");
      out.write("	color: #141414;\r\n");
      out.write("	display: -webkit-box;\r\n");
      out.write("	-webkit-line-clamp: 4;\r\n");
      out.write("	-webkit-box-orient: vertical;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	white-space: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper_next {\r\n");
      out.write("	right: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper_prev, .swiper_next {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	transform: translate(0, -50%);\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper_prev.swiper-button-disabled, .swiper_next.swiper-button-disabled\r\n");
      out.write("	{\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h3 {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".items {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	/* Creates a black border around the element */\r\n");
      out.write("}\r\n");
      out.write("/* md pick 디자인 끝 */\r\n");
      out.write("\r\n");
      out.write("/* 스와이프 디자인 */\r\n");
      out.write(".swiper-button-prev, .swiper-button-next {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("	padding: 15px 23px;\r\n");
      out.write("	border-radius: 100px;\r\n");
      out.write("	color: black !important;\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("	margin-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-button-prev:after, .swiper-button-next:after {\r\n");
      out.write("	font-size: 1.2rem !important;\r\n");
      out.write("	font-weight: 600 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-pagination-bullet {\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	background: white !important;\r\n");
      out.write("	padding: 1px 50px;\r\n");
      out.write("	border-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-pagination-bullet-active {\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	background: #FF5C00 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mdpick, .new, .category, .review {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".swiper-scrollbar {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	height: 1500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body>div.layout.main>div.swiper.mySwiper.swiper-initialized.swiper-horizontal.swiper-backface-hidden>div.swiper-scrollbar.swiper-scrollbar-horizontal>div\r\n");
      out.write("	{\r\n");
      out.write("	background-color: #FF5C00 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 스와이프 디자인 끝 */\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none !important;\r\n");
      out.write("	color: black !important;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		// 상품 클릭 시 상품상세로 이동\r\n");
      out.write("		$(\"a.goDetail\").click(function(){\r\n");
      out.write("			var pronum=$(this).attr(\"pronum\");\r\n");
      out.write("			//alert(pronum);\r\n");
      out.write("			\r\n");
      out.write("			// 디테일 페이지로 이동 #review\r\n");
      out.write("			location.href=\"index.jsp?main=product/detailpage.jsp?pro_num=\"+pronum;\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");

// 0423 17:47 작업중 - new 상품 출력
mainDao mdao = new mainDao();
List<ProductDto> nlist = new ArrayList<ProductDto>();
nlist = mdao.getNewProducts();

List<ReviewDto> rlist = new ArrayList<ReviewDto>();
rlist = mdao.getReview();

NumberFormat nf = new DecimalFormat("#,###.##원");

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"swiper mySwiper\">\r\n");
      out.write("		<div class=\"swiper-wrapper\">\r\n");
      out.write("			<div class=\"swiper-slide\">\r\n");
      out.write("				<img src=\"./image/staticImage/mainBanner2.png\" alt=\"배너 1\"\r\n");
      out.write("					style=\"width: 100%;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"swiper-slide\">\r\n");
      out.write("				<img src=\"./image/staticImage/mainBanner1.png\" alt=\"배너 2\"\r\n");
      out.write("					style=\"width: 100%;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"swiper-slide\">\r\n");
      out.write("				<img src=\"./image/staticImage/mainBanner3.png\" alt=\"배너 3\"\r\n");
      out.write("					style=\"width: 100%;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"swiper-slide\">\r\n");
      out.write("				<img src=\"./image/staticImage/mainBanner4.png\" alt=\"배너 4\"\r\n");
      out.write("					style=\"width: 100%;\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Add Pagination -->\r\n");
      out.write("		<div class=\"swiper-pagination\"></div>\r\n");
      out.write("		<!-- Add Navigation -->\r\n");
      out.write("		<div class=\"swiper-button-prev\"></div>\r\n");
      out.write("		<div class=\"swiper-button-next\"></div>\r\n");
      out.write("		<div class=\"swiper-scrollbar\"></div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div style=\"width: 1500px; margin: 0 auto;\" align=\"center;\">\r\n");
      out.write("		<!-- md pick -->\r\n");
      out.write("		<div class=\"mdpick\" style=\"margin-top: 150px;\">\r\n");
      out.write("			<span style=\"font-size: 32px;\">MD PICK</span> <img alt=\"\" src=\"./image/staticImage/Vector.png\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"swiper mySwiper\">\r\n");
      out.write("				<section\r\n");
      out.write("					class=\"xans-element- xans-product xans-product-listmain-6 xans-product-listmain xans-product-6 md_pick main_sec\">\r\n");
      out.write("					<!--\r\n");
      out.write("        $count = 9\r\n");
      out.write("        $moreview = yes\r\n");
      out.write("        -->\r\n");
      out.write("					<div class=\"list_header\">\r\n");
      out.write("						<div class=\"info\">\r\n");
      out.write("							<br>\r\n");
      out.write("							<!-- <p class=\"desc\">서브타이틀</p> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"listmain_contain\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"listmain_cont pick-swiper swiper-initialized swiper-horizontal swiper-backface-hidden\">\r\n");
      out.write("							<ul class=\"list swiper-wrapper\"\r\n");
      out.write("								id=\"swiper-wrapper-984f101776f2693cc\" aria-live=\"polite\">\r\n");
      out.write("								<li class=\"items swiper-slide xans-record- swiper-slide-active\"\r\n");
      out.write("									role=\"group\" aria-label=\"1 / 5\"\r\n");
      out.write("									style=\"width: 481.333px; margin-right: 41px;\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a href=\"index.jsp?main=product/detailpage.jsp?pro_num=436\">\r\n");
      out.write("											<picture>\r\n");
      out.write("											<img src=\"https://linetaste.com/web/product/small/202310/9929ace48353fe4c3a80da830200e7fa.jpeg\" alt=\"\"></picture>\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"infomation\">\r\n");
      out.write("										<div class=\"info\">\r\n");
      out.write("											<h4 class=\"title\">TeTaTeT Flute</h3>\r\n");
      out.write("											<p class=\"summary_desc\">램프 헤드는 가볍고 공중에 떠 있는 것처럼 보이며 테이블에 마법 같은 조명 효과를 줍니다. 휴대에도 용이한 이 조명은 테이블 주변 뿐만 아니라 모든 장소에서 독특한 분위기를 연출합니다.</p>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"items swiper-slide xans-record- swiper-slide-next\"\r\n");
      out.write("									role=\"group\" aria-label=\"2 / 5\"\r\n");
      out.write("									style=\"width: 481.333px; margin-right: 41px;\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a href=\"index.jsp?main=product/detailpage.jsp?pro_num=291\"> <picture>\r\n");
      out.write("											<img src=\"https://chapterone.kr/web/product/big/202208/6282ae7765987e2b26e5cc0440f5b154.jpg\" alt=\"\"></picture></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"infomation\">\r\n");
      out.write("										<div class=\"info\">\r\n");
      out.write("											<h4 class=\"title\">TRIPODE G5 램프</h3>\r\n");
      out.write("											<p class=\"summary_desc\">\r\n");
      out.write("												Santa & Cole은 스페인에 본사를 둔 소규모의 독립형 글로벌 디자인 제품 에디트 브랜드입니다. 책 편집자가 이야기를 다루는 것처럼, Santa & Cole은 사물을 다룹니다.</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"items swiper-slide xans-record-\" role=\"group\"\r\n");
      out.write("									aria-label=\"3 / 5\"\r\n");
      out.write("									style=\"width: 481.333px; margin-right: 41px;\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a href=\"index.jsp?main=product/detailpage.jsp?pro_num=428\"> <picture>\r\n");
      out.write("											<img src=\"https://chapterone.kr/web/product/big/202105/bb67da846f2800901558a92161cff185.jpg\" alt=\"\"></picture></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"infomation\">\r\n");
      out.write("										<div class=\"info\">\r\n");
      out.write("											<h4 class=\"title\">서큘러 라운지 3인 소파</h3>\r\n");
      out.write("											<p class=\"summary_desc\">\r\n");
      out.write("												브랜드명인 Kar는 환생을 의미하는 산스크리트어 '카르마'에 그 뿌리를 두고 있습니다.\r\n");
      out.write("												동양 철학을 기반으로 가구와 패션디자인을 아우르는 에스테틱 브랜드입니다.</p>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"items swiper-slide xans-record-\" role=\"group\"\r\n");
      out.write("									aria-label=\"4 / 5\"\r\n");
      out.write("									style=\"width: 481.333px; margin-right: 41px;\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a href=\"index.jsp?main=product/detailpage.jsp?pro_num=217\"> <picture>\r\n");
      out.write("											<img src=\"https://chapterone.kr/web/product/big/202205/38f75e4a474c665bf14a77de011a2e6b.png\" alt=\"\"></picture></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"infomation\">\r\n");
      out.write("										<div class=\"info\">\r\n");
      out.write("											<h4 class=\"title\">스토리지 SR01DWA</h3>\r\n");
      out.write("											<p class=\"summary_desc\">몬스트럭쳐는 사용자 중심의 모듈 선반 시스템 브랜드입니다. 다양성은 우리의 창의력을 끝없이 이끌어 낼 수 있습니다.</p>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"items swiper-slide xans-record-\" role=\"group\"\r\n");
      out.write("									aria-label=\"5 / 5\"\r\n");
      out.write("									style=\"width: 481.333px; margin-right: 41px;\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a href=\"index.jsp?main=product/detailpage.jsp?pro_num=245\"> <picture>\r\n");
      out.write("											<img src=\"https://chapterone.kr/web/product/big/202403/d25950984397edb368d7ee6ff99e8767.jpg\" alt=\"\"></picture></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"infomation\">\r\n");
      out.write("										<div class=\"info\">\r\n");
      out.write("											<h4 class=\"title\">스노우맨22 V2 테이블 스탠드</h3>\r\n");
      out.write("											<p class=\"summary_desc\">일광전구는 1962년 창립 이래 \r\n");
      out.write("											반세기 동안 축적된 기술과 풍부한 경험을 바탕으로 국내 조명시장을 수성하는 토종 기업입니다.</p>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<span class=\"swiper-notification\" aria-live=\"assertive\"\r\n");
      out.write("								aria-atomic=\"true\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper_next md_pick_next\" tabindex=\"0\" role=\"button\"\r\n");
      out.write("							aria-label=\"Next slide\"\r\n");
      out.write("							aria-controls=\"swiper-wrapper-984f101776f2693cc\"\r\n");
      out.write("							aria-disabled=\"false\">\r\n");
      out.write("							<img src=\"https://chapterone.kr/web/img/svg/next_btn.svg\"\r\n");
      out.write("								alt=\"다음\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"swiper_prev md_pick_prev swiper-button-disabled\"\r\n");
      out.write("							tabindex=\"-1\" role=\"button\" aria-label=\"Previous slide\"\r\n");
      out.write("							aria-controls=\"swiper-wrapper-984f101776f2693cc\"\r\n");
      out.write("							aria-disabled=\"true\">\r\n");
      out.write("							<img src=\"	https://chapterone.kr/web/img/svg/prev_btn.svg\"\r\n");
      out.write("								alt=\"이전\">\r\n");
      out.write("						</div>\r\n");
      out.write("			<script>\r\n");
      out.write("                (()=>{\r\n");
      out.write("                    const timeSwiper = new Swiper(\".pick-swiper\",{\r\n");
      out.write("                        spaceBetween: 16,\r\n");
      out.write("                        slidesPerView: 1.4,\r\n");
      out.write("                        navigation : {\r\n");
      out.write("                            nextEl : '.md_pick_next',\r\n");
      out.write("                            prevEl : '.md_pick_prev',\r\n");
      out.write("                        },\r\n");
      out.write("                        breakpoints: {\r\n");
      out.write("                            // when window width is >= 320px\r\n");
      out.write("                            767: {\r\n");
      out.write("                                spaceBetween: 30,\r\n");
      out.write("                                slidesPerView: 2,\r\n");
      out.write("                            },\r\n");
      out.write("                            1024: {\r\n");
      out.write("                                spaceBetween: 41,\r\n");
      out.write("                                slidesPerView: 3,\r\n");
      out.write("                            },\r\n");
      out.write("                        },\r\n");
      out.write("                    });\r\n");
      out.write("                })();\r\n");
      out.write("            </script>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- new -->\r\n");
      out.write("		<div class=\"new\" style=\"margin-top: 180px;\">\r\n");
      out.write("			<span style=\"font-size: 32px;\">NEW</span> <img alt=\"\" src=\"./image/staticImage/Vector.png\">\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						");

						int nline = 0;

						for (int i = 0; i < 4; i++) {
							ProductDto pdto = nlist.get(i);
						
      out.write("\r\n");
      out.write("						<td width=\"330px\" align=\"center\" style=\"padding: 20px 10px 50px;\">\r\n");
      out.write("							<a pronum=\"");
      out.print(pdto.getPro_num());
      out.write("\" class=\"goDetail\"> <img\r\n");
      out.write("								src=\"");
      out.print(pdto.getPro_main_img());
      out.write("\" style=\"padding-bottom: 8px;\">\r\n");
      out.write("								<span>");
      out.print(pdto.getPro_name());
      out.write("</span> <br> <span>");
      out.print(nf.format(pdto.getPro_price()));
      out.write("</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						</td>\r\n");
      out.write("						");

						if ((nline + 1) % 4 == 0) {
						
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"4\" align=\"center\"><a id=\"newMore\"\r\n");
      out.write("							href=\"index.jsp?main=product/newProductList.jsp\"><img alt=\"\"\r\n");
      out.write("								src=\"./image/staticImage/more_bs.png\"></a></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- category -->\r\n");
      out.write("		<div class=\"category\" style=\"margin-top: 170px;\">\r\n");
      out.write("			<table class=\"table-bordered\" style=\"width: 1200px;\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><a\r\n");
      out.write("						href=\"index.jsp?main=product/productList.jsp?cate_num=11\"><img\r\n");
      out.write("							src=\"./image/staticImage/cate_sofa.png\"></a></td>\r\n");
      out.write("					<td><a\r\n");
      out.write("						href=\"index.jsp?main=product/productList.jsp?cate_num=12\"><img\r\n");
      out.write("							src=\"./image/staticImage/cate_table.png\"></a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><a\r\n");
      out.write("						href=\"index.jsp?main=product/productList.jsp?cate_num=22\"><img\r\n");
      out.write("							src=\"./image/staticImage/cate_chair.png\"></a></td>\r\n");
      out.write("					<td><a\r\n");
      out.write("						href=\"index.jsp?main=product/productList.jsp?cate_num=4\"><img\r\n");
      out.write("							src=\"./image/staticImage/cate_lamp.png\"></a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\" style=\"height: 300px;\"><a\r\n");
      out.write("						href=\"index.jsp?main=product/productList.jsp?cate_num=5\"><img\r\n");
      out.write("							src=\"./image/staticImage/cate_etc.png\"></a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- review -->\r\n");
      out.write("		<div class=\"review\" style=\"margin-top: 180px;\">\r\n");
      out.write("			<span style=\"font-size: 32px;\">REVIEW</span> <img alt=\"\"\r\n");
      out.write("				src=\"./image/staticImage/Vector.png\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<table>\r\n");
      out.write("					");

					int rline = 0;

					// 반복문을 사용하여 이미지 출력
					for (int i = 0; i < 8; i++) {
						ReviewDto rdto = rlist.get(i);
					
      out.write("\r\n");
      out.write("					<!-- 각 행의 시작 -->\r\n");
      out.write("					");

					if (rline % 4 == 0) {
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<td width=\"330px\" align=\"center\" style=\"padding: 20px 10px 0px;\">\r\n");
      out.write("							<a pronum=\"");
      out.print(rdto.getPro_num());
      out.write("\" class=\"goDetail\">\r\n");
      out.write("								<!-- <img src=\"./image/reviewSave/etcB.jpg\" style=\"padding-bottom: 8px;\"> -->\r\n");
      out.write("								<img src=\"");
      out.print(rdto.getReview_image() );
      out.write("\" style=\"padding-bottom: 8px; height: 280px; width: 280px;\">\r\n");
      out.write("						</a>\r\n");
      out.write("						</td>\r\n");
      out.write("						<!-- 각 행의 끝 -->\r\n");
      out.write("						");

						if ((rline + 1) % 4 == 0) {
						
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("					");

					rline++;
					
      out.write("\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<!-- 마지막 행이 모자랄 경우 빈 셀로 채워주기 -->\r\n");
      out.write("					");

					if (rline % 4 != 0) {
					
      out.write("\r\n");
      out.write("					");

					int emptyCells = 4 - (rline % 4);
					
      out.write("\r\n");
      out.write("					");

					for (int j = 0; j < emptyCells; j++) {
					
      out.write("\r\n");
      out.write("					<td></td>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"4\" align=\"center\"><a id=\"newMore\" href=\"index.jsp?main=review/reviewList.jsp\">\r\n");
      out.write("							<img alt=\"\" src=\"./image/staticImage/more_bs.png\" style=\"margin-top: 50px;\"></a>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	var mySwiper = new Swiper('.mySwiper', {\r\n");
      out.write("		loop : true,\r\n");
      out.write("		spaceBetween : 30,\r\n");
      out.write("		centeredSlides : true,\r\n");
      out.write("		autoplay : {\r\n");
      out.write("			delay : 3500,\r\n");
      out.write("			disableOnInteraction : false,\r\n");
      out.write("		},\r\n");
      out.write("		pagination : {\r\n");
      out.write("			el : '.swiper-pagination',\r\n");
      out.write("			clickable : true,\r\n");
      out.write("		},\r\n");
      out.write("		navigation : {\r\n");
      out.write("			nextEl : '.swiper-button-next',\r\n");
      out.write("			prevEl : '.swiper-button-prev',\r\n");
      out.write("		},\r\n");
      out.write("		effect : 'slide', // 'slide', 'fade', 'cube', 'coverflow' 또는 'flip' 중 선택\r\n");
      out.write("		scrollbar : {\r\n");
      out.write("			el : '.swiper-scrollbar',\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
